# 4ID-A setup

s4idundulator:
  device: undulators
  baseline: True
  timeout: 2

hhl_mirror:
  device: hhl_mirror
  baseline: True

wb_slit: 
  device: wbslt
  baseline: True

monochromator:
  device: mono
  baseline: True

labjacks:
  device: labjack_4ida
  baseline: False

camera_4ida_up:
  device: flag_camera_4ida_up
  baseline: False

camera_4ida_down:
  device: flag_camera_4ida_down
  baseline: False

flags:
  device: [flag_4ida_up, flag_4ida_down]
  baseline: [True, True]

jj_slits:
  device: monoslt
  baseline: True

phaseplates:
  device: [pr1, pr2, pr3, pr_setup]
  baseline: [True, True, True]

energy_device:
  device: energy
  baseline: True

qxscan_setup:
  device: qxscan_params
  baseline: True

data_management:
  device: [dm_experiment, dm_workflow]
  baseline: [True, True]
