# 4ID-B setup

scaler_ctr8:
  module: scaler_4idCTR8
  class: LocalScalerCH
  prefix: 4idCTR8_1:scaler1
  parameters:
    labels: ['detector', 'scaler']
  run_default: True
  baseline: True

ctr8:
  module: usb_ctr8
  class: CustomMeasCompCtr
  prefix: "4idCTR8_1:"
  parameters:
    labels: ["detector", "scaler"]
  baseline: True

# camera_4idb:
#   device: flag_camera_4idb
#   baseline: False
#   timeout: 5

# flags:
#   device: flag_4idb
#   baseline: True

# diamond_window_table:
#   device: diamond_window
#   baseline: True

# table_4idb:
#   device: midtable_4idb
#   baseline: True

# tetramms:
#   device: [tetramm_4idb, tetramm_4idb_ro]
#   baseline: [False, True]

# polarimeter:
#   device: pol
#   baseline: False

# jj_slits:
#   device: bslt
#   baseline: True

# filters_device:
#   device: bfilter
#   baseline: True

# chopper_device:
#   device: chopper
#   baseline: True

# kb_mirrors:
#   device: kbb
#   baseline: True

# electromagnet:
#   device: emag
#   baseline: True
