# 4ID-A setup

scaler_4idCTR8:
  device: scaler_ctr8
  baseline: True

usb_ctr8:
  device: ctr8
  baseline: True

4idb_camera:
  device: flag_camera_4idb
  baseline: False
  timeout: 5

flags:
  device: flag_4idb
  baseline: True

diamond_window_table:
  device: diamond_window
  baseline: True