# 4ID-A setup

xbpm_4idg:
  device: gxbpm
  baseline: True

transfocator_device:
  device: transfocator
  baseline: True

# Filters

jj_slits:
  device: gslt
  baseline: True

# KB mirror

polar_diffractometer:
  device: [huber_euler, huber_euler_psi, huber_hp, huber_hp_psi]
  baseline: [False, False, False, False]

# simulated_fourc_vertical:
#   device: fourc
#   baseline: True

# pva_control:
#   device: positioner_stream
#   baseline: True

# softgluezynq:
#   device: sgz
#   baseline: True

# nanopositioner:
#   device: diff_nano
#   baseline: True

ad_eiger1M:
  device: eiger
  baseline: False

# xspress:
#   device: vortex
#   baseline: False
