# 4ID-A setup

laser_sample_stage:
  device: sx
  baseline: True

laser_sample_stage:
  device: sy
  baseline: True

laser_sample_stage:
  device: sz
  baseline: True

ventus_laser:
  device: laser
  baseline: True

ad_lightfield:
  device: spectrometer
  baseline: True

ge_controller:
  device: ge_apply
  baseline: True

ge_controller:
  device: ge_release
  baseline: True
