# Guarneri-style device YAML configuration

instrument.devices.aps_xbpm.MyXBPM:
- name: aps_xbpm
  prefix: S04
  labels: ["source"]

instrument.devices.aps_undulator.PolarUndulatorPair:
- name: undulators
  prefix: "S04ID:"
  labels: ["source", "energy device"]

instrument.devices.aps_status.StatusAPS:
- name: status_aps
  prefix: ""
  labels: ["source", "status"]

instrument.devices.hhl_mirror.ToroidalMirror:
- name: hhl_mirror
  prefix: "4idHHLM:"
  labels: ["4ida", "mirror"]

instrument.devices.monochromator.MonoDevice:
- name: mono
  prefix: "4idVDCM:"
  labels: ["4ida", "monochromator", "energy device"]

instrument.devices.labjacks.CustomLabJackT7:
- name: labjack_4ida
  prefix: "4idaSoft:LJ:"
  labels: ["4ida"]

- name: labjack_4idb
  prefix: "4idLabJackT7_1:"
  labels: ["4idb"]

instrument.devices.ad_vimba.VimbaDetector:
- name: flagcam_hhl
  prefix: "4idaPostMirrBeam:"
  labels: ["4ida", "camera", "detector", "flag"]

- name: flagcam_mono
  prefix: "4idaPostMonoBeam:"
  labels: ["4ida", "camera", "detector", "flag"]

- name: flagcam_toro
  prefix: "4idbPostToroBeam:"
  labels: ["4idb", "camera", "detector", "flag"]

ophyd.EpicsMotor:
- name: flagmotor_hhl
  prefix: "4idVDCM:m6"
  labels: ["4ida", "motor", "flag"]

- name: flagmotor_mono
  prefix: "4idVDCM:m7"
  labels: ["4ida", "motor", "flag"]

- name: flagmotor_toro
  prefix: "4idbSoft:m3"
  labels: ["4idb", "motor", "flag"]

instrument.devices.jj_slits.SlitDevice:
- name: monoslt
  PV: "4idVDCM:"
  motorsDict: {top: m14, bot: m13, out: m16, inb: m15}
  slitnum: 2
  labels: ["4ida", "slit"]

- name: bslt
  PV: "4idbSoft:"
  motorsDict: {top: m11, bot: m10, out: m13, inb: m12}
  slitnum: 1
  labels: ["4idb", "slit"]

- name: gslt
  PV: "4idgSoft:"
  motorsDict: {top: m44, bot: m43, out: m46, inb: m45}
  slitnum: 1
  labels: ["4idg", "slit"]

instrument.devices.phaseplates.PRDevice:
- name: pr1
  prefix: "4ida:"
  prnum: 1
  motorsDict: {x: m1, y: m2, th: m4}
  labels: ["4ida", "phase retarder", "energy device", "track_energy"]

- name: pr2
  prefix: "4ida:"
  prnum: 2
  motorsDict: {x: m6, y: m7, th: m9}
  labels: ["4ida", "phase retarder", "energy device", "track_energy"]

instrument.devices.phaseplates.PRDeviceBase:
- name: pr3
  prefix: "4ida:"
  motorsDict: {x: m10, y: m11, th: m12}
  labels: ["4ida", "phase retarder", "energy device", "track_energy"]

instrument.devices.energy_device.EnergySignal:
- name: energy
  value: 10
  kind: hinted
  labels: ["energy device"]

# This is messing up the logger.
# apstools.devices.DM_WorkflowConnector:
# - name: dm_workflow
#   labels: ["dm"]

ophyd.Signal:
- name: dm_experiment
  value: ""
  labels: ["dm"]

instrument.devices.polar_status.Status4ID:
- name: status_polar
  prefix: "PA:04ID:"
  labels: ["status"]

instrument.devices.shutters.PolarShutter:
- name: ashutter
  prefix: ""
  state_pv: "PA:04ID:A_BEAM_PRESENT"
  open_pv: "PC:04ID:FES_OPEN_REQUEST"
  close_pv: "PC:04ID:FES_CLOSE_REQUEST"
  labels: ["4ida", "shutter"]

apstools.devices.ApsPssShutterWithStatus:
- name: bshutter
  prefix: ""
  state_pv: "PA:04ID:B_BEAM_PRESENT"
  open_pv: "PC:04ID:SBS_OPEN_REQUEST"
  close_pv: "PC:04ID:SBS_CLOSE_REQUEST"
  labels: ["4idb", "shutter"]

instrument.devices.scaler.LocalScalerCH:
- name: scaler1
  prefix: "4idCTR8_1:scaler1"
  labels: ["detector", "scaler"]

- name: scaler2
  prefix: "4idCTR8_1:scaler2"
  labels: ["detector", "scaler"]

instrument.devices.usb_ctr8.CustomMeasCompCtr:
- name: ctr8
  prefix: "4idCTR8_1:"
  labels: ["detector"]

instrument.devices.diamond_window_table.WindowStages:
- name: diamond_window
  prefix: "4idbSoft:"
  labels: ["4ida"]

instrument.devices.table_4idb.Table4idb:
- name: midtable_4idb
  prefix: "4idbSoft:"
  labels: ["4idb"]

instrument.devices.quadems.TetrAMMRO:
- name: btetramm
  prefix: "4idbSoft:TetrAMM:"
  labels: ["detector", "xbpm"]

instrument.devices.quadems.SydorEMRO:
- name: gsydor
  prefix: "4idgSydor:T4U_BPM:"
  labels: ["detector", "xbpm"]

- name: hsydor
  prefix: "4idhSydor:T4U_BPM:"
  labels: ["detector", "xbpm"]

instrument.devices.polarimeter.PolAnalyzer:
- name: pol
  prefix: "4idbSoft:"
  labels: ["4idb"]

instrument.devices.filters_device.APSFilter:
- name: bfilter
  prefix: "4idbSoft:filter:"
  labels: ["4idb", "filter"]

instrument.devices.chopper_device.ChopperDevice:
- name: chopper
  prefix: "4idChopper:"
  labels: ["4idb"]

instrument.devices.chopper_device.ChopperDevice:
- name: chopper
  prefix: "4idChopper:"
  labels: ["4idb"]

instrument.devices.kb_mirrors.KBMirror:
- name: bkb
  prefix: "4idbSoft:"
  labels: ["4idb", "optics"]

instrument.devices.electromagnet.Magnet2T:
- name: emag
  prefix: ""
  labels: ["4idb", "magnet"]

instrument.devices.xbpm_4idg.XBPM:
- name: gxbpm
  prefix: "4idgSoft:"
  labels: ["4idg"]

instrument.devices.transfocator_device.TransfocatorClass:
- name: transfocator
  prefix: "4idPyCRL:CRL4ID:"
  labels: ["4idg", "optics", "track_energy"]

instrument.devices.filters_device_avs.APSFilter:
- name: gfilter
  prefix: "4idPyFilter:FL1:"
  labels: ["4idg", "filter"]

apstools.devices.LakeShore336Device:
- name: temp_4idg
  prefix: "4idgSoft:LS336:cryo:"
  labels: ["4idg", "temperature"]

instrument.devices.polar_diffractometer.CradleDiffractometer:
- name: huber_euler
  prefix: "4idgSoft:"
  labels: ["4idg", "diffractometer"]

instrument.devices.polar_diffractometer.HPDiffractometer:
- name: huber_hp
  prefix: "4idgSoft:"
  labels: ["4idg", "diffractometer"]

instrument.devices.polar_diffractometer.CradlePSI:
- name: huber_euler_psi
  prefix: "4idgSoft:"
  engine: psi
  labels: ["4idg", "diffractometer"]

instrument.devices.polar_diffractometer.HPPSI:
- name: huber_hp_psi
  prefix: "4idgSoft:"
  engine: psi
  labels: ["4idg", "diffractometer"]

instrument.devices.ad_eiger1M.Eiger1MDetector:
- name: eiger
  prefix: "4idEiger:"
  labels: ["4idg", "detector"]

instrument.devices.qxscan_device.QxscanParams:
- name: qxscan_setup
  labels: ["qxscan", "energy device"]
