# Configuration for the Bluesky instrument package.

# identify the version of this iconfig.yml file
ICONFIG_VERSION: 2.0.0

# Add additional configuration for use with your instrument.
STATION: raman

### The short name for the databroker catalog.
DATABROKER_CATALOG: &databroker_catalog 4id_polar

### RunEngine configuration
RUN_ENGINE:
    DEFAULT_METADATA:
        beamline_id: 4id-polar
        instrument_name: 4ID-Raman
        proposal_id: internal
        databroker_catalog: *databroker_catalog

    ### EPICS PV to use for the `scan_id`.
    ### Default: `RE.md["scan_id"]` (not using an EPICS PV)
    # SCAN_ID_PV: f"{IOC}bluesky_scan_id"

    ### Directory to "autosave" the RE.md dictionary (uses PersistentDict).
    ### Default: HOME/.config/Bluesky_RunEngine_md'
    MD_PATH: /home/beams/POLAR/.config/Bluesky_RunEngine_md_raman

    ### The progress bar is nice to see,
    ### except when it clutters the output in Jupyter notebooks.
    ### Default: True
    USE_PROGRESS_BAR: false

### Best Effort Callback Configurations
### Defaults: all true (except no plots in queueserver)
# BEC:
#     BASELINE: false
#     HEADING: false
#     PLOTS: false
#     TABLE: false


### APS Data Management
### Use bash shell, deactivate all conda environments, source this file:
DM_SETUP_FILE: /home/dm/etc/dm.setup.sh
DM_ROOT_PATH: /gdata/dm/4IDD
DM_USE_PATH: true

DSERV_ROOT_PATH: &dserv_root /net/s4data/export/sector4/4idd

### Detectors
AREA_DETECTOR:
    # TODO: switch to the Voyager-based path structure: "/gdata/..."
    HDF5_FILE_TEMPLATE: "%s/%s_%6.6d"
    HDF5_FILE_EXTENSION: h5
    EIGER_1M:
        # IOC_FILES_ROOT: /gdata/dm/4IDD  # unnecessary, uses DM or EPICS value
        DEFAULT_FOLDER: /net/s4data/export/sector4/4idd/bluesky_images/eiger1M
        ALLOW_PLUGIN_WARMUP: true
    VORTEX:
        IOC_FILES_ROOT: *dserv_root
        DEFAULT_FOLDER: /net/s4data/export/sector4/4idd/bluesky_images/vortex
        ALLOW_PLUGIN_WARMUP: true
    LIGHTFIELD:
        IOC_FILES_ROOT: Z:\4idd
        BLUESKY_FILES_ROOT: *dserv_root
        RELATIVE_DEFAULT_FOLDER: bluesky_images/vortex
        ALLOW_PLUGIN_WARMUP: true

### Support for known output file formats.
### Uncomment to use.  If undefined, will not write that type of file.
### Each callback should apply its configuration from here.
NEXUS_DATA_FILES:
    FILE_EXTENSION: hdf
    WARN_MISSING_CONTENT: false
SPEC_DATA_FILES:
    FILE_EXTENSION: dat

# ----------------------------------

OPHYD:
    ### Control layer for ophyd to communicate with EPICS.
    ### Default: PyEpics
    ### Choices: "PyEpics" or "caproto"
    # CONTROL_LAYER: caproto

    ### default timeouts (seconds)
    TIMEOUTS:
        PV_READ: &TIMEOUT 5
        PV_WRITE: *TIMEOUT
        PV_CONNECTION: *TIMEOUT

LOGGING:
    ### Uncomment any of these to override the defaults
    # MAX_BYTES: 1000000
    NUMBER_OF_PREVIOUS_BACKUPS: 9
    # LOG_PATH: /tmp
    ### If LOG_PATH undefined, this session will log into PWD/logs/
    ### where PWD is present working directory when session is started

# Control detail of exception traces in IPython (console and notebook).
XMODE_DEBUG_LEVEL: Minimal
